# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Charsets-Japanese
version:      0.01
version_from: lib/Catalyst/Plugin/Charsets/Japanese.pm
installdirs:  site
requires:
    Catalyst:                      5.23
    Jcode:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.29
